version: '3'

services:
  
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - backend-network
    command: ["yarn", "dev"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
