import Login from "@/components/Login";

export const metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <div className="w-svw h-svh flex justify-center items-center">
      <Login/>
    </div>
  );
}
