apiVersion: v1
kind: ConfigMap
metadata:
  name: express-app-config
  namespace: my-express
data:
  PORT_NUMBER: "4001"
  SERVER: "express-app-service"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
  namespace: my-express
  labels:
    app: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: dedsec2002/testing:my-express-app 
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: express-app-config
      imagePullSecrets:
        - name: docker-login
---
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  namespace: my-express # Namespace should be here under metadata
spec:
  type: LoadBalancer
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
