const exchanges_2_documents = require('../models/schema')

async function feeding_exchange_2_documents(){
    try {
        await exchanges_2_documents.insertMany(
            [
                {
                  "id": "bybit_spot",
                  "name": "Bybit",
                  "year_established": 2018,
                  "country": "British Virgin Islands",
                  "description": "Bybit is a cryptocurrency exchange that offers a professional platform featuring an ultra-fast matching engine, excellent customer service and multilingual community support for crypto traders of all levels. Established in March 2018, Bybit currently serves more than 10 million users and institutions offering access to over 100 assets and contracts across Spot, Futures and Options, launchpad projects, earn products, an NFT Marketplace and more. Bybit is a proud partner of Formula One racing team, Oracle Red Bull Racing, esports teams NAVI, Astralis, Alliance, Virtus.pro, Made in Brazil (MIBR), City Esports, and Oracle Red Bull Racing Esports, and association football (soccer) teams Borussia Dortmund and Avispa Fukuoka.",
                  "url": "https://www.bybit.com",
                  "image": "https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1706864649",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 1,
                  "trade_volume_24h_btc": 54123.06881729408,
                  "trade_volume_24h_btc_normalized": 49248.749319158625
                },
                {
                  "id": "okex",
                  "name": "OKX",
                  "year_established": 2017,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.okx.com",
                  "image": "https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1706864283",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 2,
                  "trade_volume_24h_btc": 36410.734032294546,
                  "trade_volume_24h_btc_normalized": 36410.734032294546
                },
                {
                  "id": "gdax",
                  "name": "Coinbase Exchange",
                  "year_established": 2012,
                  "country": "United States",
                  "description": "",
                  "url": "https://www.coinbase.com/",
                  "image": "https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1706864258",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 3,
                  "trade_volume_24h_btc": 35913.097788463696,
                  "trade_volume_24h_btc_normalized": 35913.097788463696
                },
                {
                  "id": "huobi",
                  "name": "HTX",
                  "year_established": 2013,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.huobi.com",
                  "image": "https://assets.coingecko.com/markets/images/25/small/logo_V_colour_black.png?1706864260",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 4,
                  "trade_volume_24h_btc": 30760.421460437443,
                  "trade_volume_24h_btc_normalized": 23856.496468935664
                },
                {
                  "id": "kraken",
                  "name": "Kraken",
                  "year_established": 2011,
                  "country": "United States",
                  "description": "",
                  "url": "https://www.kraken.com/",
                  "image": "https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1706864265",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 5,
                  "trade_volume_24h_btc": 16408.34375779922,
                  "trade_volume_24h_btc_normalized": 16408.34375779922
                },
                {
                  "id": "kucoin",
                  "name": "KuCoin",
                  "year_established": 2017,
                  "country": "Seychelles",
                  "description": "Launched in September 2017, KuCoin is a global cryptocurrency exchange with its operational headquarters in Seychelles. As a user-oriented platform with a focus on inclusiveness and community action reach, it offers over 800 digital assets and currently provides Spot trading, Margin trading, P2P Fiat trading, Futures trading, Staking, and Lending to its 30 million users in more than 200 countries and regions. KuCoin is currently one of the top 5 crypto exchanges. In 2023, KuCoin was named one of the Best Crypto Exchanges by Forbes and recognized as a highly commended global exchange in Finder's 2023 Global Cryptocurrency Trading Platform Awards. Learn more at https://www.kucoin.com.",
                  "url": "https://www.kucoin.com/",
                  "image": "https://assets.coingecko.com/markets/images/61/small/kucoin.png?1706864282",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 6,
                  "trade_volume_24h_btc": 12409.221736492851,
                  "trade_volume_24h_btc_normalized": 12409.221736492851
                },
                {
                  "id": "crypto_com",
                  "name": "Crypto.com Exchange",
                  "year_established": 2019,
                  "country": "Malta",
                  "description": "Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards",
                  "url": "https://crypto.com/exchange",
                  "image": "https://assets.coingecko.com/markets/images/589/small/h2oMjPp6_400x400.jpg?1706864542",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 7,
                  "trade_volume_24h_btc": 15040.891065131844,
                  "trade_volume_24h_btc_normalized": 11249.11207876918
                },
                {
                  "id": "hashkey_exchange",
                  "name": "HashKey Exchange",
                  "year_established": 2018,
                  "country": "Hong Kong",
                  "description": "On a mission to set the bar for virtual asset exchanges in compliance, safety, and security, Hash Blockchain Limited (HashKey Exchange) is Hong Kong's first licensed virtual asset exchange for retail users. HashKey Exchange has recently received approval from the Securities and Futures Commission (SFC) of Hong Kong to operate a virtual asset trading platform under Type 1 (Dealing in securities) licence and Type 7 (Providing automated trading services) licence. As HashKey Group's exchange business, HashKey Exchange provides all-in-one trading services for both professional investors (PI) and retail investors. HashKey Exchange has obtained ISO 27001 (Information Security) and ISO 27701 (Data Privacy) management system certifications.",
                  "url": "https://www.hashkey.com/",
                  "image": "https://assets.coingecko.com/markets/images/1206/small/hashkey_2.png?1706869603",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 8,
                  "trade_volume_24h_btc": 469.2421395891784,
                  "trade_volume_24h_btc_normalized": 469.2421395891784
                },
                {
                  "id": "binance_us",
                  "name": "Binance US",
                  "year_established": 2019,
                  "country": "United States",
                  "description": "",
                  "url": "https://www.binance.us/",
                  "image": "https://assets.coingecko.com/markets/images/469/small/Binance.png?1706864454",
                  "has_trading_incentive": false,
                  "trust_score": 10,
                  "trust_score_rank": 9,
                  "trade_volume_24h_btc": 304.9736714426721,
                  "trade_volume_24h_btc_normalized": 304.9736714426721
                },
                {
                  "id": "binance",
                  "name": "Binance",
                  "year_established": 2017,
                  "country": "Cayman Islands",
                  "description": "",
                  "url": "https://www.binance.com/",
                  "image": "https://assets.coingecko.com/markets/images/52/small/binance.jpg?1706864274",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 10,
                  "trade_volume_24h_btc": 317318.1317395294,
                  "trade_volume_24h_btc_normalized": 127696.20986126339
                },
                {
                  "id": "bitget",
                  "name": "Bitget",
                  "year_established": 2018,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.bitget.com/",
                  "image": "https://assets.coingecko.com/markets/images/540/small/2023-07-25_21.47.43.jpg?1706864507",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 11,
                  "trade_volume_24h_btc": 28151.28614403476,
                  "trade_volume_24h_btc_normalized": 23898.809593395265
                },
                {
                  "id": "mxc",
                  "name": "MEXC",
                  "year_established": 2018,
                  "country": "Seychelles",
                  "description": "Established in April 2018, MEXC is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.",
                  "url": "https://www.mexc.com/",
                  "image": "https://assets.coingecko.com/markets/images/409/small/MEXC_logo_square.jpeg?1706864416",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 12,
                  "trade_volume_24h_btc": 21944.38869562979,
                  "trade_volume_24h_btc_normalized": 21944.38869562979
                },
                {
                  "id": "gate",
                  "name": "Gate.io",
                  "year_established": null,
                  "country": "Cayman Islands",
                  "description": "Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.",
                  "url": "https://www.gate.io/",
                  "image": "https://assets.coingecko.com/markets/images/60/small/gate_io_logo1.jpg?1706864280",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 13,
                  "trade_volume_24h_btc": 42690.588571779124,
                  "trade_volume_24h_btc_normalized": 18431.33424862588
                },
                {
                  "id": "bingx",
                  "name": "BingX",
                  "year_established": 2018,
                  "country": "British Virgin Islands",
                  "description": "Founded in 2018, BingX is a leading crypto exchange, serving over 10 million users worldwide. BingX offers diversified products and services, including spot, derivatives, copy trading, and asset management – all designed for the evolving needs of users, from beginners to professionals. \r\nBingX is committed to providing a trustworthy platform that empowers users with innovative tools and features to elevate their trading proficiency. In 2024, BingX proudly became Chelsea FC's principal partner, marking an exciting debut in the world of sports.",
                  "url": "https://bingx.com/",
                  "image": "https://assets.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1706864837",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 14,
                  "trade_volume_24h_btc": 11293.87700881556,
                  "trade_volume_24h_btc_normalized": 11293.87700881556
                },
                {
                  "id": "deepcoin",
                  "name": "Deepcoin",
                  "year_established": 2018,
                  "country": "Seychelles",
                  "description": "Deepcoin Exchange offers groundbreaking tools for you to buy and sell over 120 cryptocurrencies. Since 2018, we have provided a secure and reliable way for you to invest in spot and futures trading to our over 1 million users.",
                  "url": "https://www.deepcoin.com/",
                  "image": "https://assets.coingecko.com/markets/images/1005/small/deepcoin.jpeg?1706864992",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 15,
                  "trade_volume_24h_btc": 11014.397670987426,
                  "trade_volume_24h_btc_normalized": 5918.462551353093
                },
                {
                  "id": "fastex",
                  "name": "Fastex",
                  "year_established": null,
                  "country": "Lithuania",
                  "description": "",
                  "url": "https://exchange.fastex.com/",
                  "image": "https://assets.coingecko.com/markets/images/1091/small/fastex.png?1706865112",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 16,
                  "trade_volume_24h_btc": 2588.3836707923133,
                  "trade_volume_24h_btc_normalized": 2588.3836707923133
                },
                {
                  "id": "bitfinex",
                  "name": "Bitfinex",
                  "year_established": 2012,
                  "country": "British Virgin Islands",
                  "description": "",
                  "url": "https://www.bitfinex.com",
                  "image": "https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1706864245",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 17,
                  "trade_volume_24h_btc": 2302.597452204863,
                  "trade_volume_24h_btc_normalized": 2109.7288870430825
                },
                {
                  "id": "bitstamp",
                  "name": "Bitstamp",
                  "year_established": 2011,
                  "country": "Luxembourg",
                  "description": "",
                  "url": "https://links.bitstamp.net/c/2223866/1100037/14006",
                  "image": "https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1706864251",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 18,
                  "trade_volume_24h_btc": 3036.933198230167,
                  "trade_volume_24h_btc_normalized": 1989.2126819491446
                },
                {
                  "id": "gemini",
                  "name": "Gemini",
                  "year_established": 2014,
                  "country": "United States",
                  "description": "",
                  "url": "https://www.gemini.com/",
                  "image": "https://assets.coingecko.com/markets/images/50/small/gemini.png?1706864273",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 19,
                  "trade_volume_24h_btc": 1062.265118382657,
                  "trade_volume_24h_btc_normalized": 1062.265118382657
                },
                {
                  "id": "wootrade",
                  "name": "WOO X",
                  "year_established": 2019,
                  "country": "Seychelles",
                  "description": "WOO Network is a deep liquidity network connecting traders, exchanges, institutions, and DeFi platforms with democratized access to the best-in-class liquidity and trading execution at lower or zero cost. Its flagship, WOO X, is a professional trading platform featuring customizable modules and lower to zero fees complete with deep liquidity. WOO Network was founded by Kronos Research, a quantitative trading firm generating $5-10B in daily volume.",
                  "url": "https://woo.org/",
                  "image": "https://assets.coingecko.com/markets/images/683/small/woo.png?1706864629",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 20,
                  "trade_volume_24h_btc": 827.7709236952745,
                  "trade_volume_24h_btc_normalized": 582.5161753259223
                },
                {
                  "id": "coinspro",
                  "name": "Coins.ph",
                  "year_established": null,
                  "country": "Philippines",
                  "description": "",
                  "url": "https://coins.ph/about",
                  "image": "https://assets.coingecko.com/markets/images/999/small/coinspro.png?1706864987",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 21,
                  "trade_volume_24h_btc": 167.71385942271948,
                  "trade_volume_24h_btc_normalized": 167.71385942271948
                },
                {
                  "id": "luno",
                  "name": "Luno",
                  "year_established": 2013,
                  "country": "Singapore",
                  "description": "",
                  "url": "https://www.luno.com",
                  "image": "https://assets.coingecko.com/markets/images/33/small/RGB_LUNO_SYMBOL_NAVY_BLUE_1.png?1706864266",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 22,
                  "trade_volume_24h_btc": 118.1900656155437,
                  "trade_volume_24h_btc_normalized": 118.1900656155437
                },
                {
                  "id": "okcoin",
                  "name": "Okcoin",
                  "year_established": 2013,
                  "country": "United States",
                  "description": "Founded in 2013, Okcoin is a US-headquartered cryptocurrency exchange serving 190+ countries and territories. The platform enables retail and institutional investors to purchase digital assets using local currencies, with a mission to make crypto easy for everyone, including first-time buyers. Okcoin was the first centralized exchange to offer direct entry into decentralized finance (DeFi) with Earn, a tool for earning APY through decentralized lending, liquidity pools, staking, and more. In addition, Okcoin offers institutional trading tools and APIs to asset managers, venture capital and hedge funds, retail brokers, payment processors, and more. Follow Okcoin on Twitter at @Okcoin and visit okcoin.com for more information.",
                  "url": "https://www.okcoin.com/",
                  "image": "https://assets.coingecko.com/markets/images/415/small/okcoin_Logomark_SatoshiBlack.png?1706864417",
                  "has_trading_incentive": false,
                  "trust_score": 9,
                  "trust_score_rank": 23,
                  "trade_volume_24h_btc": 0.5000615647236434,
                  "trade_volume_24h_btc_normalized": 0.5000615647236434
                },
                {
                  "id": "upbit",
                  "name": "Upbit",
                  "year_established": 2017,
                  "country": "South Korea",
                  "description": "",
                  "url": "https://upbit.com",
                  "image": "https://assets.coingecko.com/markets/images/117/small/upbit.png?1706864294",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 24,
                  "trade_volume_24h_btc": 61287.57501631695,
                  "trade_volume_24h_btc_normalized": 19173.08433975341
                },
                {
                  "id": "whitebit",
                  "name": "WhiteBIT",
                  "year_established": 2018,
                  "country": "Lithuania",
                  "description": "",
                  "url": "https://whitebit.com",
                  "image": "https://assets.coingecko.com/markets/images/418/small/800_800.jpg?1706864419",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 25,
                  "trade_volume_24h_btc": 18237.38779539968,
                  "trade_volume_24h_btc_normalized": 18237.38779539968
                },
                {
                  "id": "lbank",
                  "name": "LBank",
                  "year_established": 2015,
                  "country": "British Virgin Islands",
                  "description": "LBank is a globally based centralized exchange (CEX) platform established in 2015. The platform allows users to buy and sell major crypto assets like Bitcoin (BTC) and Ethereum (ETH) in over 149 fiat currencies, with over 20 payment methods. The company has licenses from the National Futures Association, Italian Organismo degli Agenti e dei Mediatori, and money services businesses in the United States & Canada. The LBank exchange has over 9 million users and accepts clients from over 200 regions.\r\nLBank Exchange provides its users with crypto trading, specialized financial derivatives, and professional asset management services.\r\n ",
                  "url": "https://www.lbank.com",
                  "image": "https://assets.coingecko.com/markets/images/118/small/LBank_logo.png?1706864296",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 26,
                  "trade_volume_24h_btc": 16942.449571122408,
                  "trade_volume_24h_btc_normalized": 16265.114452268728
                },
                {
                  "id": "bitmart",
                  "name": "BitMart",
                  "year_established": 2017,
                  "country": "Cayman Islands",
                  "description": "",
                  "url": "https://www.bitmart.com/en",
                  "image": "https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1706864341",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 27,
                  "trade_volume_24h_btc": 17746.60678719936,
                  "trade_volume_24h_btc_normalized": 15551.779078363734
                },
                {
                  "id": "digifinex",
                  "name": "DigiFinex",
                  "year_established": 2018,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.digifinex.com/",
                  "image": "https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1706864334",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 28,
                  "trade_volume_24h_btc": 15540.083960155256,
                  "trade_volume_24h_btc_normalized": 13609.608805046308
                },
                {
                  "id": "xt",
                  "name": "XT.COM",
                  "year_established": 2018,
                  "country": "Seychelles",
                  "description": "By consistently expanding its ecosystem, XT.COM is dedicated to providing users with the most secure, trusted, and hassle-free digital asset trading services. Our exchange is built from a desire to give everyone access to digital assets regardless where you are. \r\n\r\nFounded in 2018, XT.COM now serves more than 6 million registered users, over 500,000+ monthly active users and 40+ million users in the ecosystem. Covering a rich variety of  trading categories together with a NFT aggregated marketplace,  our platform strives to cater to its large user base by providing a secure, trusted and intuitive trading experience.\r\n\r\nAs the world’s first social-infused digital assets trading platform, XT.COM also supports social networking platform based transactions to make our crypto services more accessible to users all over the world. Furthermore, to ensure optimal data integrity and security, we see user security as our top priority at XT.COM. ",
                  "url": "https://www.xt.com/",
                  "image": "https://assets.coingecko.com/markets/images/404/small/logo400x400.png?1706864415",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 29,
                  "trade_volume_24h_btc": 9353.902199717217,
                  "trade_volume_24h_btc_normalized": 9353.902199717217
                },
                {
                  "id": "bitrue",
                  "name": "Bitrue",
                  "year_established": 2018,
                  "country": "Singapore",
                  "description": "",
                  "url": "https://www.bitrue.com/",
                  "image": "https://assets.coingecko.com/markets/images/254/small/unnamed_%281%29.png?1706864350",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 30,
                  "trade_volume_24h_btc": 27383.99457431691,
                  "trade_volume_24h_btc_normalized": 9234.108563977188
                },
                {
                  "id": "coinw",
                  "name": "CoinW",
                  "year_established": 2017,
                  "country": "United Arab Emirates",
                  "description": "What Is CoinW?\r\nCoinW stands as a pinnacle in the world of crypto trading platforms, where our unwavering commitment to security, transparency, and user-centric principles sets us apart. Powered by cutting-edge technology, boasting deep liquidity, and offering support for a diverse array of cryptocurrencies, we have cultivated a vast and dedicated user base, solidifying our position as one of the most secure exchanges globally.\r\n\r\nDedicated to upholding the highest regulatory standards, we prioritize security, transparency, and compliance to contribute actively to the advancement of the crypto industry. At CoinW, we take pride in serving over 10 million users worldwide, earning our reputation as a beacon of security and reliability in the dynamic realm of cryptocurrency. Join us on this journey, where your assets are safeguarded, and your trading experience is elevated to new heights.\r\n\r\nWho Are the Founders of CoinW?\r\nIncepted in 2017 by a fusion of crypto, cybersecurity, and finance virtuosos, CoinW has established 16 Localized Trading Service Centers spanning 13 distinct countries. With a robust workforce comprising over 1,000 talents representing 30 diverse nations, CoinW stands as the quintessential embodiment of a global and professional entity.\r\n\r\nWhen Did CoinW Launch?\r\nCoinW was launched in 2017.\r\n\r\nWhere Is CoinW Located?\r\nBased in the vibrant city of Dubai, UAE, CoinW has expanded its global presence with 16 Localized Trading Service Centers spanning 13 countries. Our reach extends to key locations such as Dubai, Singapore, Turkey, South Korea, Japan, the Philippines, Malaysia, Australia, Vietnam, India, Nigeria, Canada, and Russia. Serving customers in over 200 regions and countries, CoinW is dedicated to providing a seamless and localized trading experience.\r\n\r\nAs a forward-thinking crypto trading platform, we prioritize collaboration with international regulatory bodies and organizations, contributing to the establishment of a safe and secure environment for our users.\r\n\r\nWhat Coins Are Supported on CoinW?\r\nCoinW boasts a vast array of over 1,000 listed crypto tokens, offering more than 500 spot trading pairs. Popular coins include BTC, ETH, BGB, XRP, PEPE, DOGE, SHIB, BNB, LTC, APT and more.\r\n\r\nHow Much Are CoinW Fees?\r\nWhen users conduct currency transactions on CoinW, the platform will charge users a certain fee to support the operation of the platform.User fees for makers and takers on the platform will be charged according to different rules. Currently, the basic fees for maker and takers on the platform are both 0.2%.\r\n\r\nIs It Possible To Use Leverage or Margin Trading on CoinW?\r\nCoinW empowers traders seeking strategic leverage through our comprehensive options for both spot and Futures trading. Our platform offers unparalleled flexibility, allowing users to utilize leverage ratios of up to 200x in Futures and 6x in ETF trading. This means that traders can amplify their positions, opening the door to potential profit maximization in crypto market.\r\n",
                  "url": "https://www.coinw.com/",
                  "image": "https://assets.coingecko.com/markets/images/1172/small/coinw_new_logo.png?1713879109",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 31,
                  "trade_volume_24h_btc": 8280.528186025305,
                  "trade_volume_24h_btc_normalized": 8280.528186025305
                },
                {
                  "id": "latoken",
                  "name": "LATOKEN",
                  "year_established": 2017,
                  "country": "Cayman Islands",
                  "description": "",
                  "url": "https://latoken.com/",
                  "image": "https://assets.coingecko.com/markets/images/124/small/latoken.png?1706864301",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 32,
                  "trade_volume_24h_btc": 7993.2597470737455,
                  "trade_volume_24h_btc_normalized": 7993.2597470737455
                },
                {
                  "id": "tapbit",
                  "name": "Tapbit",
                  "year_established": 2019,
                  "country": "United States",
                  "description": "Tapbit offers secure and stable trading services for global investors in mainstream crypto assets such as BTC, ETH, SOL, and USDC. The platform holds the MSB fiat currency business license issued by the U.S. federal government, the MSB fiat currency business license issued by the Canadian government, the NFA general financial license, and the crypto and forex business license issued by SVGFSA. Additionally, we safeguard all your assets on Tapbit through a multi-million-dollar insurance fund Tapbit provides users with cutting-edge technology, featuring a core aggregation engine that stands as one of the most advanced technological products in the current market. With fault tolerance and exceptional processing speed, it can address concurrent issues arising from instantaneous high volumes of transactions and settlements. Our security measures include banking-grade SSL encryption, multi-signature capabilities, and hot & cold wallet separation technology, all working together to rigorously protect the security of all user assets  Tapbit stands out as one of the safest and most reliable cryptocurrency service platforms in the current market. Global investors can utilize and benefit from the platform without worrying about potential risks associated with the field, thanks to the application of advanced technology and innovative algorithms.",
                  "url": "https://www.tapbit.com/",
                  "image": "https://assets.coingecko.com/markets/images/1374/small/Tapbit-Logo.png?1706865388",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 33,
                  "trade_volume_24h_btc": 4739.178809954073,
                  "trade_volume_24h_btc_normalized": 3499.37329134267
                },
                {
                  "id": "backpack_exchange",
                  "name": "Backpack Exchange ",
                  "year_established": 2023,
                  "country": "British Virgin Islands",
                  "description": "A next-gen cryptocurrency exchange. ",
                  "url": "https://backpack.exchange/",
                  "image": "https://assets.coingecko.com/markets/images/1387/small/backpack.jpeg?1708663541",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 34,
                  "trade_volume_24h_btc": 5273.142799107608,
                  "trade_volume_24h_btc_normalized": 3185.5453934123125
                },
                {
                  "id": "bitmax",
                  "name": "AscendEX (BitMax)",
                  "year_established": 2018,
                  "country": "Singapore",
                  "description": "AscendEX (formerly BitMax) is a leading global digital asset financial platform founded by a group of Wall Street quantitative trading veterans in 2018, building on core value of “Efficiency, Resilience and Transparency.” \r\n \r\nDriven by its continuous innovative product development and early-mover advantage in strategic alignment with the leading projects from DeFi ecosystem, AscendEX offers trading services across over 200 trading pairs across cash, margin, and futures products, in particular margin trading of over 50 tokens in cross-asset collateral mode and futures trading in both cross-asset and isolated margin modes.",
                  "url": "https://ascendex.com/en/global-digital-asset-platform",
                  "image": "https://assets.coingecko.com/markets/images/277/small/%E5%8E%9F%E8%89%B2.png?1706864357",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 35,
                  "trade_volume_24h_btc": 3014.647447507393,
                  "trade_volume_24h_btc_normalized": 2731.725398464728
                },
                {
                  "id": "phemex",
                  "name": "Phemex",
                  "year_established": 2019,
                  "country": "Singapore",
                  "description": "Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 5 million active users in over 200 countries, Phemex supports 150+ trading pairs with up to 100x leverage.\r\n\r\n-  Fee Structure: 0.1% for both maker and taker\r\n-  Contract Fee Structure: 0.01% for maker and 0.06% for taker\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.",
                  "url": "https://phemex.com/",
                  "image": "https://assets.coingecko.com/markets/images/564/small/phemex_logo.png?1706864519",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 36,
                  "trade_volume_24h_btc": 1959.0940440670736,
                  "trade_volume_24h_btc_normalized": 1865.8187714248932
                },
                {
                  "id": "pointpay",
                  "name": "PointPay",
                  "year_established": 2018,
                  "country": "Saint Vincent and the Grenadines",
                  "description": "",
                  "url": "https://exchange.pointpay.io/",
                  "image": "https://assets.coingecko.com/markets/images/1060/small/pointpay.png?1706865085",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 37,
                  "trade_volume_24h_btc": 1893.0530018775726,
                  "trade_volume_24h_btc_normalized": 1865.1727951942344
                },
                {
                  "id": "dextrade",
                  "name": "Dex-Trade",
                  "year_established": 2019,
                  "country": "Belize",
                  "description": "Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing",
                  "url": "https://dex-trade.com/",
                  "image": "https://assets.coingecko.com/markets/images/380/small/Dex-Trade.png?1706864395",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 38,
                  "trade_volume_24h_btc": 1377.278949897495,
                  "trade_volume_24h_btc_normalized": 1377.278949897495
                },
                {
                  "id": "btse",
                  "name": "BTSE",
                  "year_established": 2018,
                  "country": "British Virgin Islands",
                  "description": "BTSE is a leading digital asset exchange that empowers users by offering a simple and secure way to trade. Its growing suite of financial services is designed to bridge traditional finance with digital assets solutions. BTSE's innovative technology offers a set of digital financial solutions featuring multi-currency spot and derivatives trading, in addition to NFT and exchange white labels, over-the-counter (OTC) trading, asset management, and payment gateways. Additionally, BTSE provides an all-in-one order book, strict security protocols, an insurance fund, cold storage for more than 99% of assets and no withdrawal limits on over 12 fiat currencies and 100 cryptocurrencies.",
                  "url": "https://www.btse.com/",
                  "image": "https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1706864449",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 39,
                  "trade_volume_24h_btc": 1135.0796843250441,
                  "trade_volume_24h_btc_normalized": 1135.0796843250441
                },
                {
                  "id": "exmo",
                  "name": "EXMO",
                  "year_established": 2013,
                  "country": "United Kingdom",
                  "description": "",
                  "url": "https://exmo.com/",
                  "image": "https://assets.coingecko.com/markets/images/59/small/tt_ava.jpg?1706864278",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 40,
                  "trade_volume_24h_btc": 933.4522744438159,
                  "trade_volume_24h_btc_normalized": 933.4522744438159
                },
                {
                  "id": "bitso",
                  "name": "Bitso",
                  "year_established": 2014,
                  "country": "Gibraltar",
                  "description": "",
                  "url": "https://bitso.com",
                  "image": "https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1706864249",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 41,
                  "trade_volume_24h_btc": 545.3458150236604,
                  "trade_volume_24h_btc_normalized": 545.3458150236604
                },
                {
                  "id": "indodax",
                  "name": "Indodax",
                  "year_established": 2014,
                  "country": "Indonesia",
                  "description": "",
                  "url": "https://indodax.com",
                  "image": "https://assets.coingecko.com/markets/images/3/small/logogram-Indodax-new-_JPG_format.jpg?1706864243",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 42,
                  "trade_volume_24h_btc": 417.9156896196217,
                  "trade_volume_24h_btc_normalized": 417.9156896196217
                },
                {
                  "id": "bitbank",
                  "name": "Bitbank",
                  "year_established": 2016,
                  "country": "Japan",
                  "description": "",
                  "url": "https://bitbank.cc/",
                  "image": "https://assets.coingecko.com/markets/images/122/small/bitbank.jpg?1706864298",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 43,
                  "trade_volume_24h_btc": 387.9589157352262,
                  "trade_volume_24h_btc_normalized": 387.9589157352262
                },
                {
                  "id": "max_maicoin",
                  "name": "Max Maicoin",
                  "year_established": null,
                  "country": "Taiwan",
                  "description": "",
                  "url": "https://max.maicoin.com",
                  "image": "https://assets.coingecko.com/markets/images/218/small/max.jpg?1706864331",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 44,
                  "trade_volume_24h_btc": 288.59369069308934,
                  "trade_volume_24h_btc_normalized": 288.59369069308934
                },
                {
                  "id": "bitopro",
                  "name": "BitoPro",
                  "year_established": 2018,
                  "country": "Taiwan",
                  "description": "",
                  "url": "https://www.bitopro.com/",
                  "image": "https://assets.coingecko.com/markets/images/358/small/bitopro_coingecko_250x250_%281%29.png?1706864386",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 45,
                  "trade_volume_24h_btc": 273.7657703406998,
                  "trade_volume_24h_btc_normalized": 273.7657703406998
                },
                {
                  "id": "xeggex",
                  "name": "XeggeX",
                  "year_established": 2021,
                  "country": "Seychelles",
                  "description": "Founded in 2021, XeggeX.com strives to provide its users with the best trading experience and give small and medium market cap assets a reliable trading hub. Our goal is to maintain a fast and user friendly system while also concentrating on security to keep users, data, and assets safe. Security of our users' data & assets is always our top priority and we are focused on building an easy to use digital asset trading platform for everyone to enjoy.",
                  "url": "https://xeggex.com",
                  "image": "https://assets.coingecko.com/markets/images/1299/small/XeggeX_Logo_200.png?1706865292",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 46,
                  "trade_volume_24h_btc": 51.972783646965034,
                  "trade_volume_24h_btc_normalized": 51.972783646965034
                },
                {
                  "id": "nonkyc_io",
                  "name": "Nonkyc.io",
                  "year_established": 2023,
                  "country": "Seychelles",
                  "description": "About NonKyc.io Founded in 2023, NonKyc.io strives to provide its users with the best trading experience and give small and medium market cap assets a reliable trading hub. Our goal is to maintain a fast and user friendly system while also concentrating on security to keep users, data, and assets safe. Security of our users' data & assets is always our top priority and we are focused on building an easy to use digital asset trading platform for everyone to enjoy.  The NonKYC platform system is NOT from some predesigned script package or preexisting codebase. It has been created from the ground up by professional developers who are well experienced in Cryptocurrency. NonKYC has been designed to scale horizontally as we grow to become a top tier exchange.",
                  "url": "https://nonkyc.io",
                  "image": "https://assets.coingecko.com/markets/images/1281/small/NKYC-Logo.png?1706865279",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 47,
                  "trade_volume_24h_btc": 49.59357860966199,
                  "trade_volume_24h_btc_normalized": 49.59357860966199
                },
                {
                  "id": "kuna",
                  "name": "Kuna Exchange",
                  "year_established": null,
                  "country": "United Kingdom",
                  "description": "",
                  "url": "https://kuna.io/",
                  "image": "https://assets.coingecko.com/markets/images/97/small/kuna_exchange.png?1706864284",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 48,
                  "trade_volume_24h_btc": 43.29085721112841,
                  "trade_volume_24h_btc_normalized": 43.29085721112841
                },
                {
                  "id": "nice_hash",
                  "name": "NiceHash",
                  "year_established": null,
                  "country": "Slovenia",
                  "description": "",
                  "url": "https://www.nicehash.com",
                  "image": "https://assets.coingecko.com/markets/images/546/small/logo_small_light.png?1706864513",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 49,
                  "trade_volume_24h_btc": 7.691784779409818,
                  "trade_volume_24h_btc_normalized": 7.691784779409818
                },
                {
                  "id": "bitmex_spot",
                  "name": "BitMEX",
                  "year_established": null,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.bitmex.com/spot/",
                  "image": "https://assets.coingecko.com/markets/images/866/small/bitmex.jpeg?1706864881",
                  "has_trading_incentive": false,
                  "trust_score": 8,
                  "trust_score_rank": 50,
                  "trade_volume_24h_btc": 2.1533112050038667,
                  "trade_volume_24h_btc_normalized": 2.1533112050038667
                },
                {
                  "id": "p2pb2b",
                  "name": "P2B",
                  "year_established": 2018,
                  "country": "Lithuania",
                  "description": "P2B is a top crypto platform in Europe and has gotten into the TOP-3 Crypto Exchanges by growth speed. It offers the best go-to-market experience to diverse crypto startups. At the exchange, investors can find a wide variety of newly-launched tokens.\r\n\r\n\r\nThe platform attracts new crypto projects due to the high-level liquidity of the crypto exchange. One of the essential benefits of the crypto exchange is the high-level security of every launch and operation. It's in the TOP-15 in Cer.Live security rate. \r\n\r\n\r\nThe exchange has 6-year-old experience in the crypto field and has presented more than 2,000 crypto projectsʼ launches. The go-to-market team of the exchange has designed a well-thought strategy for marketing and promoting newly-launched projects to enhance their liquidity and involve new investors.\r\n\r\n\r\nP2B offers a top-grade launchpad with extended functionality for newly-launched crypto projects. The platform offers additional liquidity services to support a token price after a listing stage and avoid a price drop. It doesn't have limitations, a ticket system, and doesn't hold tokens. The total amount of funds raised through launchpads is already more than $10 million, and the top results from one launchpad are $2+ million.\r\n\r\n\r\nP2B is popular among newly-launched crypto projects due to easy-to-go onboarding, a loyal listing requirement for the 1st listing, expertise, and well-designed tools for the project's promotion. The exchange also contributes to the development of WEB 3.0 by creating the Fund of Rising Stars to support projects with high potential and strong ideas.\r\n\r\n\r\nJoin the prosperous P2B community—the #1 place to be in crypto.\r\n\r\nGet your exciting trading experience and earn fast and securely with 24/7 support.\r\n\r\n",
                  "url": "https://p2pb2b.com/",
                  "image": "https://assets.coingecko.com/markets/images/251/small/ow0xng56_400x400.jpeg?1706864347",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 51,
                  "trade_volume_24h_btc": 16797.06096750567,
                  "trade_volume_24h_btc_normalized": 15251.138559049565
                },
                {
                  "id": "biconomy",
                  "name": "Biconomy",
                  "year_established": 2019,
                  "country": "Canada",
                  "description": "Biсonomy is a Canadian cryptocurrency exchange founded on October 1, 2019.\r\nThe exchange has a Canadian trading license and has also recently received a US MSB license.\r\nBiconomy only hosts high-quality projects and coins. It is also possible to buy a cryptocurrency for fiat using the AdvCash solution.",
                  "url": "https://www.biconomy.com/",
                  "image": "https://assets.coingecko.com/markets/images/633/small/biconomy-cex.png?1706864578",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 52,
                  "trade_volume_24h_btc": 10261.508956361931,
                  "trade_volume_24h_btc_normalized": 9733.539799397682
                },
                {
                  "id": "bithumb",
                  "name": "Bithumb",
                  "year_established": 2014,
                  "country": "South Korea",
                  "description": "",
                  "url": "https://www.bithumb.com/",
                  "image": "https://assets.coingecko.com/markets/images/6/small/bithumb_BI.png?1706864248",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 53,
                  "trade_volume_24h_btc": 9349.125234609683,
                  "trade_volume_24h_btc_normalized": 8650.403146090686
                },
                {
                  "id": "bitvenus_spot",
                  "name": "BitVenus",
                  "year_established": 2018,
                  "country": "British Virgin Islands",
                  "description": "Founded in May 2018, our exchange offers reliable and efficient 24x7 spot and derivatives trading services. Our commitment to continual innovation has allowed us to launch state-of-the-art features, such as a copy trading function, which facilitates both novice and seasoned traders. This persistent focus on enhancement, fueled by a team of seasoned industry professionals, ensures that our product offerings remain top-tier, competitive, and user-friendly. We highly prioritize customer service, boasting a dedicated team ready to provide high-quality support whenever needed. Our dedicated compliance team works meticulously to ensure our trading environment is secure, adhering strictly to all regulatory requirements. All these efforts come together to create a trading platform that offers security, support, and innovative features that make trading both easy and rewarding.",
                  "url": "https://www.bitvenus.com/",
                  "image": "https://assets.coingecko.com/markets/images/1253/small/BitVenus_logo.png?1709559502",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 54,
                  "trade_volume_24h_btc": 16431.656251923254,
                  "trade_volume_24h_btc_normalized": 6845.112803809207
                },
                {
                  "id": "toobit",
                  "name": "Toobit",
                  "year_established": 2022,
                  "country": "Cayman Islands",
                  "description": "",
                  "url": "https://www.toobit.com/",
                  "image": "https://assets.coingecko.com/markets/images/1139/small/Toobit_logo400X400.png?1706865157",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 55,
                  "trade_volume_24h_btc": 7114.769980457848,
                  "trade_volume_24h_btc_normalized": 6512.014142566537
                },
                {
                  "id": "bigone",
                  "name": "BigONE",
                  "year_established": 2017,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://bigone.com",
                  "image": "https://assets.coingecko.com/markets/images/100/small/qcFFufEY_400x400.jpg?1706864287",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 56,
                  "trade_volume_24h_btc": 6417.883536521162,
                  "trade_volume_24h_btc_normalized": 5099.131057712838
                },
                {
                  "id": "bitvavo",
                  "name": "Bitvavo",
                  "year_established": 2018,
                  "country": "Netherlands",
                  "description": "",
                  "url": "https://bitvavo.com/en",
                  "image": "https://assets.coingecko.com/markets/images/714/small/bitvavo-mark-square-black.png?1706864670",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 57,
                  "trade_volume_24h_btc": 4215.045555724484,
                  "trade_volume_24h_btc_normalized": 4215.045555724484
                },
                {
                  "id": "azbit",
                  "name": "Azbit",
                  "year_established": null,
                  "country": "Seychelles",
                  "description": "Azbit is a new generation exchange offering the most in-demand services on the market. Spot exchange, margin trading, crypto-backed loans.",
                  "url": "https://azbit.com/",
                  "image": "https://assets.coingecko.com/markets/images/787/small/logo.png?1706864819",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 58,
                  "trade_volume_24h_btc": 2919.464860681771,
                  "trade_volume_24h_btc_normalized": 2919.464860681771
                },
                {
                  "id": "pionex",
                  "name": "Pionex",
                  "year_established": 2019,
                  "country": "British Virgin Islands",
                  "description": "",
                  "url": "https://www.pionex.com",
                  "image": "https://assets.coingecko.com/markets/images/1026/small/pionex.png?1706865056",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 59,
                  "trade_volume_24h_btc": 5455.263090379154,
                  "trade_volume_24h_btc_normalized": 2410.8274849731765
                },
                {
                  "id": "btcturk",
                  "name": "BtcTurk | Kripto",
                  "year_established": 2013,
                  "country": "Turkey",
                  "description": "",
                  "url": "https://kripto.btcturk.com/en",
                  "image": "https://assets.coingecko.com/markets/images/223/small/btctrurk_kripto.png?1706864333",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 60,
                  "trade_volume_24h_btc": 3392.692176583131,
                  "trade_volume_24h_btc_normalized": 1778.8287514653132
                },
                {
                  "id": "bitunix",
                  "name": "Bitunix",
                  "year_established": 2021,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.bitunix.com/",
                  "image": "https://assets.coingecko.com/markets/images/1185/small/APP_icon_1024.png?1706865197",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 61,
                  "trade_volume_24h_btc": 1635.782798216273,
                  "trade_volume_24h_btc_normalized": 1635.782798216273
                },
                {
                  "id": "bydfi",
                  "name": "BYDFi",
                  "year_established": 2020,
                  "country": null,
                  "description": "",
                  "url": "https://www.bydfi.com/en",
                  "image": "https://assets.coingecko.com/markets/images/1186/small/photo_2024-03-20_11-10-03.jpg?1710914231",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 62,
                  "trade_volume_24h_btc": 1331.238936368063,
                  "trade_volume_24h_btc_normalized": 1331.238936368063
                },
                {
                  "id": "bitflyer",
                  "name": "bitFlyer",
                  "year_established": 2014,
                  "country": "Japan",
                  "description": "",
                  "url": "https://bitflyer.com/en-eu/",
                  "image": "https://assets.coingecko.com/markets/images/5/small/bitFlyer-logo.png?1706864247",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 63,
                  "trade_volume_24h_btc": 1166.5316050873244,
                  "trade_volume_24h_btc_normalized": 1166.5316050873244
                },
                {
                  "id": "coincheck",
                  "name": "Coincheck",
                  "year_established": 2014,
                  "country": "Japan",
                  "description": null,
                  "url": "https://coincheck.com/",
                  "image": "https://assets.coingecko.com/markets/images/18/small/Coincheck.jpg?1706864255",
                  "has_trading_incentive": null,
                  "trust_score": 7,
                  "trust_score_rank": 64,
                  "trade_volume_24h_btc": 970.2133446033673,
                  "trade_volume_24h_btc_normalized": 970.2133446033673
                },
                {
                  "id": "coinex",
                  "name": "CoinEx",
                  "year_established": 2017,
                  "country": "Samoa",
                  "description": "",
                  "url": "https://www.coinex.com/",
                  "image": "https://assets.coingecko.com/markets/images/135/small/coinex.jpg?1706864305",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 65,
                  "trade_volume_24h_btc": 853.2601655538754,
                  "trade_volume_24h_btc_normalized": 853.2601655538754
                },
                {
                  "id": "cryptology",
                  "name": "Cryptology",
                  "year_established": 2018,
                  "country": "Lithuania",
                  "description": "",
                  "url": "https://cryptology.com/",
                  "image": "https://assets.coingecko.com/markets/images/287/small/logo-symbol.png?1706864361",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 66,
                  "trade_volume_24h_btc": 777.5742324589843,
                  "trade_volume_24h_btc_normalized": 777.5742324589843
                },
                {
                  "id": "bitkub",
                  "name": "Bitkub",
                  "year_established": 2018,
                  "country": "Thailand",
                  "description": "",
                  "url": "https://www.bitkub.com",
                  "image": "https://assets.coingecko.com/markets/images/249/small/bitkub.png?1706864345",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 67,
                  "trade_volume_24h_btc": 713.9478910013661,
                  "trade_volume_24h_btc_normalized": 713.9478910013661
                },
                {
                  "id": "korbit",
                  "name": "Korbit",
                  "year_established": 2013,
                  "country": "South Korea",
                  "description": "",
                  "url": "https://www.korbit.co.kr/",
                  "image": "https://assets.coingecko.com/markets/images/28/small/korbit-logo.png?1706864263",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 68,
                  "trade_volume_24h_btc": 372.00737467939695,
                  "trade_volume_24h_btc_normalized": 372.00737467939695
                },
                {
                  "id": "bitazza",
                  "name": "Bitazza",
                  "year_established": 2021,
                  "country": "Thailand",
                  "description": "Bitazza is ASEAN's locally-based digital asset platform. ",
                  "url": "https://trade.bitazza.com/gl/exchange/",
                  "image": "https://assets.coingecko.com/markets/images/837/small/btzlogo200x200_darkgreen.png?1706864859",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 69,
                  "trade_volume_24h_btc": 331.54670112407325,
                  "trade_volume_24h_btc_normalized": 331.54670112407325
                },
                {
                  "id": "independent_reserve",
                  "name": "Independent Reserve",
                  "year_established": 2013,
                  "country": "Australia",
                  "description": "",
                  "url": "https://www.independentreserve.com/",
                  "image": "https://assets.coingecko.com/markets/images/389/small/x_V5Jquo_400x400.png?1706864404",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 70,
                  "trade_volume_24h_btc": 289.07369342626197,
                  "trade_volume_24h_btc_normalized": 289.07369342626197
                },
                {
                  "id": "okcoin-japan",
                  "name": "OKCoin Japan",
                  "year_established": 2017,
                  "country": "Japan",
                  "description": "Our company was established as the Japanese corporation of OK Group and is operating under a structure compliant with Japanese laws and regulations as a registered cryptocurrency exchange business with the Financial Services Agency. Additionally, by utilizing the group's advanced technology, products, and the know-how accumulated over the years, we are flexibly responding to market needs and will contribute to the revitalization of Japan's WEB3.0 (crypto asset-related business).",
                  "url": "https://www.okcoin.jp/",
                  "image": "https://assets.coingecko.com/markets/images/1420/small/OKJlogo%E6%96%B9%E5%BD%A2.jpg?1707298108",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 71,
                  "trade_volume_24h_btc": 241.97767135858214,
                  "trade_volume_24h_btc_normalized": 241.97767135858214
                },
                {
                  "id": "bullish_com",
                  "name": "Bullish",
                  "year_established": 2021,
                  "country": "Gibraltar",
                  "description": "",
                  "url": "https://bullish.com/",
                  "image": "https://assets.coingecko.com/markets/images/905/small/bullish_com.png?1706864904",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 72,
                  "trade_volume_24h_btc": 12838.566739340848,
                  "trade_volume_24h_btc_normalized": 209.16574339532377
                },
                {
                  "id": "kanga",
                  "name": "Kanga",
                  "year_established": 2018,
                  "country": "Belize",
                  "description": "",
                  "url": "https://kanga.exchange/",
                  "image": "https://assets.coingecko.com/markets/images/852/small/KaNGa_logo.png?1706864870",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 73,
                  "trade_volume_24h_btc": 195.789582452616,
                  "trade_volume_24h_btc_normalized": 195.789582452616
                },
                {
                  "id": "slex",
                  "name": "Slex",
                  "year_established": 2023,
                  "country": "Costa Rica",
                  "description": "",
                  "url": "https://slex.io/",
                  "image": "https://assets.coingecko.com/markets/images/1527/small/slex_200x200_2.png?1711335245",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 74,
                  "trade_volume_24h_btc": 208.2241514954895,
                  "trade_volume_24h_btc_normalized": 184.1866157922374
                },
                {
                  "id": "bitcastle",
                  "name": "bitcastle",
                  "year_established": 2019,
                  "country": "Lithuania",
                  "description": "bitcastle is all in one global platform including crypto trading, FX trading and binary option trading first launched in July 2019.  In May 2022, bitcastle renewed it's platform with a brand new user interface, new features and token listings. With offices in Singapore, Vietnam and Japan, bitcastle maximizes the strengths of the diverse team with various experiences to deliver the best financial services for its users.  Notable features of the platform include 0% trading fee for major currency pairs and High & Low binary trading option. bitcastle High & Low option allows users to see return on their investment in as little as 5 seconds, which is the fastest period in the world. bitcastle aims to be a platform that can be enjoyed by both seasoned traders as well as beginners.  CASTLE is bitcastle's native token. CASTLE can be used to reduce transaction fees on the platform by up to 60%. At selected intervals, 20% of bitcastle's profits will be used to buy back CASTLE tokens, and burn them.  The bitcastle apps is now available for both android and IOS, enabling users to access it's platform.",
                  "url": "https://bitcastle.io/en",
                  "image": "https://assets.coingecko.com/markets/images/1341/small/bitcastle_logo.png?1706865343",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 75,
                  "trade_volume_24h_btc": 1932.868277439552,
                  "trade_volume_24h_btc_normalized": 173.32235015681778
                },
                {
                  "id": "btcmarkets",
                  "name": "BTCMarkets",
                  "year_established": null,
                  "country": "Australia",
                  "description": "",
                  "url": "https://www.btcmarkets.net/",
                  "image": "https://assets.coingecko.com/markets/images/237/small/BTCMarkets_logo2.png?1706864340",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 76,
                  "trade_volume_24h_btc": 116.12303032773359,
                  "trade_volume_24h_btc_normalized": 116.12303032773359
                },
                {
                  "id": "cex",
                  "name": "CEX.IO",
                  "year_established": 2013,
                  "country": "United Kingdom",
                  "description": "",
                  "url": "https://trade.cex.io/",
                  "image": "https://assets.coingecko.com/markets/images/56/small/main-icon.png?1706864277",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 77,
                  "trade_volume_24h_btc": 86.44138694865464,
                  "trade_volume_24h_btc_normalized": 86.44138694865464
                },
                {
                  "id": "coindcx",
                  "name": "CoinDCX",
                  "year_established": 2018,
                  "country": "Singapore",
                  "description": "Started on April 7th, 2018, CoinDCX is a Singapore-based company that specializes in crypto-enabled financial services. Offering you the simplest yet robust trading environment to trade 200+ coins, 500+ markets, and 150+ coins on leverage at lightning speed.\r\n\r\nWith major fintech innovations going across the world, DCX is bringing a revolution with its crypto-based products. DCX is not just for the banked or unbanked, DCX aims to build an all-inclusive ecosystem by bringing trust between the trustless. DCX is focused on developing borderless financial services which ensure faster, simpler, and uninterrupted flow of capital.\r\nThrough its array of products, DCX is upgrading lives every day.\r\n",
                  "url": "https://www.coindcx.com",
                  "image": "https://assets.coingecko.com/markets/images/520/small/coindcx.png?1706864493",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 78,
                  "trade_volume_24h_btc": 36.28180714150766,
                  "trade_volume_24h_btc_normalized": 36.28180714150766
                },
                {
                  "id": "emirex",
                  "name": "Emirex",
                  "year_established": 2014,
                  "country": "United Arab Emirates",
                  "description": "Emirex is a groundbreaking platform that unites an exchange and a marketplace, providing users with the opportunity to exchange various stores of value for digital assets. Our mission is to harness the potential of digital assets and contribute to a world with greater economic freedom through open, fair, and censorship-resistant networks that serve humanity better.\r\n\r\nEstablished in Estonia, Emirex has expanded its reach and now offers a professional trading platform that caters to the needs of investors and issuers of digital assets in the Middle East, Africa, Asia, and Europe. Our goal is to facilitate exposure to Middle Eastern wealth and enable the free movement of value around the world, ultimately promoting social welfare.\r\n\r\nAs a European licensed platform, Emirex is uniquely positioned to bridge the gap between East and West. With operations anchored in Estonia and a wider presence in the Czech Republic and Lithuania, we ensure a tailored and localized service for our diverse users.\r\n\r\nEmirex.ee vs. Emirex.com\r\nEmirex operates through two primary domains to cater to the distinct regulatory requirements and preferences of our global user base:\r\n\r\n1. Emirex.ee: Rooted in Estonia, this platform stands as a testament to our origins, offering a secure and compliant trading environment under Estonia's, Czech, and Canada's regulatory frameworks.\r\n\r\n2. Emirex.com: Our expansive platform, regulated by the authorities of the Czech Republic and Lithuania, is designed to meet the diverse standards and requirements of these jurisdictions.\r\n\r\nFor clarity, any websites or platforms bearing the \"Emirex\" name or branding outside of these two domains are not affiliated with or endorsed by Emirex. We prioritize the trust and safety of our community and always encourage users to verify domain names for authenticity.\r\n\r\nEmirex's journey is one of continuous evolution. We pride ourselves on staying abreast of the latest industry developments, ensuring full regulatory compliance, and nurturing an ambitious roadmap for the future. Our team at Emirex is unwaveringly dedicated to proactive engagement with the broader community of traders, investors, issuers, and partners. We firmly believe that our platform's growth and success hinge on the active participation of our diverse ecosystem members. By fostering collaboration, innovation, and transparency, together, we can reshape the digital economy's landscape.\r\n\r\nJoin Emirex as we lead the way in connecting East and West, driven by the transformative power of digital assets and pioneering blockchain technology.  ",
                  "url": "https://www.emirex.com/",
                  "image": "https://assets.coingecko.com/markets/images/592/small/Emirex.png?1706864545",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 79,
                  "trade_volume_24h_btc": 32.04403432689437,
                  "trade_volume_24h_btc_normalized": 18.543084891461938
                },
                {
                  "id": "delta_spot",
                  "name": "Delta Exchange",
                  "year_established": null,
                  "country": "Jamaica",
                  "description": "",
                  "url": "https://www.delta.exchange/app/spot/trade/",
                  "image": "https://assets.coingecko.com/markets/images/642/small/delta_spot.jpg?1706864589",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 80,
                  "trade_volume_24h_btc": 6.085782223802627,
                  "trade_volume_24h_btc_normalized": 6.085782223802627
                },
                {
                  "id": "nominex",
                  "name": "Nominex",
                  "year_established": 2019,
                  "country": "Seychelles",
                  "description": "New trading platform for convenient trading experience with low fees and numerous instruments. \r\n\r\nAbsolutely unique affiliate program that allows to earn from an infinite number of referral levels, compared to 2-3 levels at all other exchanges. \r\n\r\nA unique model for the free 2 phases distribution of the native NMX token.\r\n\r\nAdvanced Trading Instruments – using Stop, Stop Limit, Trailing Stop, Scaled and other types of orders brings some kind of trading automation without the need to develop a trading bot, which allows to easily get more profit while trading.",
                  "url": "https://www.nominex.io",
                  "image": "https://assets.coingecko.com/markets/images/530/small/logo-200x200.png?1706864500",
                  "has_trading_incentive": false,
                  "trust_score": 7,
                  "trust_score_rank": 81,
                  "trade_volume_24h_btc": 4.2144618494385355,
                  "trade_volume_24h_btc_normalized": 4.2144618494385355
                },
                {
                  "id": "uniswap_v3",
                  "name": "Uniswap V3 (Ethereum)",
                  "year_established": 2018,
                  "country": null,
                  "description": "",
                  "url": "https://app.uniswap.org/#/swap",
                  "image": "https://assets.coingecko.com/markets/images/665/small/uniswap-v3.png?1706864608",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 82,
                  "trade_volume_24h_btc": 15526.273165255208,
                  "trade_volume_24h_btc_normalized": 15526.273165255208
                },
                {
                  "id": "orangex",
                  "name": "OrangeX",
                  "year_established": 2021,
                  "country": "Seychelles",
                  "description": "Registered in Seychelles, OrangeX is a trading company with the combined strengths of skilled staff and the experience of core financial technical expertise. ",
                  "url": "https://www.orangex.com/",
                  "image": "https://assets.coingecko.com/markets/images/1272/small/Subtract.png?1706865272",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 83,
                  "trade_volume_24h_btc": 20597.06081668278,
                  "trade_volume_24h_btc_normalized": 7052.637518316707
                },
                {
                  "id": "cointr",
                  "name": "CoinTR Pro",
                  "year_established": 2022,
                  "country": "Lithuania",
                  "description": "",
                  "url": "https://www.cointr.pro/",
                  "image": "https://assets.coingecko.com/markets/images/1028/small/cointr.png?1706865058",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 84,
                  "trade_volume_24h_btc": 6698.745106016378,
                  "trade_volume_24h_btc_normalized": 5861.932629849204
                },
                {
                  "id": "pancakeswap-v3-bsc",
                  "name": "Pancakeswap V3 (BSC)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://pancakeswap.finance/swap",
                  "image": "https://assets.coingecko.com/markets/images/1111/small/pancakeswap.jpeg?1706865132",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 85,
                  "trade_volume_24h_btc": 4893.129862155342,
                  "trade_volume_24h_btc_normalized": 4893.129862155342
                },
                {
                  "id": "uniswap_v3_arbitrum",
                  "name": "Uniswap V3 (Arbitrum One)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://app.uniswap.org/#/swap",
                  "image": "https://assets.coingecko.com/markets/images/702/small/uniswap-v3.png?1706864655",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 86,
                  "trade_volume_24h_btc": 4042.4728182388917,
                  "trade_volume_24h_btc_normalized": 4042.4728182388917
                },
                {
                  "id": "uniswap_v2",
                  "name": "Uniswap V2 (Ethereum)",
                  "year_established": 2018,
                  "country": null,
                  "description": "",
                  "url": "https://app.uniswap.org/#/swap?use=V2",
                  "image": "https://assets.coingecko.com/markets/images/535/small/256x256_Black-1.png?1706864503",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 87,
                  "trade_volume_24h_btc": 2805.9542227938205,
                  "trade_volume_24h_btc_normalized": 2805.9542227938205
                },
                {
                  "id": "uniswap-v3-base",
                  "name": "Uniswap V3 (Base)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://app.uniswap.org/#/swap",
                  "image": "https://assets.coingecko.com/markets/images/1212/small/uniswap-v3.jpg?1706865221",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 88,
                  "trade_volume_24h_btc": 2233.2541765266565,
                  "trade_volume_24h_btc_normalized": 2233.2541765266565
                },
                {
                  "id": "probit",
                  "name": "ProBit Global",
                  "year_established": 2017,
                  "country": "Seychelles",
                  "description": "",
                  "url": "https://www.probit.com/",
                  "image": "https://assets.coingecko.com/markets/images/370/small/probit.png?1706864390",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 89,
                  "trade_volume_24h_btc": 8009.799409963002,
                  "trade_volume_24h_btc_normalized": 1729.0051512368989
                },
                {
                  "id": "paribu",
                  "name": "Paribu",
                  "year_established": null,
                  "country": "Turkey",
                  "description": null,
                  "url": "https://www.paribu.com/",
                  "image": "https://assets.coingecko.com/markets/images/136/small/paribu.jpg?1706864307",
                  "has_trading_incentive": null,
                  "trust_score": 6,
                  "trust_score_rank": 90,
                  "trade_volume_24h_btc": 2329.4030963489977,
                  "trade_volume_24h_btc_normalized": 1429.1184481066318
                },
                {
                  "id": "weex",
                  "name": "WEEX",
                  "year_established": 2018,
                  "country": "Singapore",
                  "description": "WEEX is a prominent centralized cryptocurrency exchange that was established in 2018 with a $100 million investment from Singapore's leading blockchain investment firm. It aims to provide comprehensive and trustworthy services in the cryptocurrency trading field. With low trading fees and user-friendly access, WEEX facilitates the trading of various cryptocurrencies and futures. In addition to spot trading, it also offers options for futures trading and OTC trading, catering to different investment preferences.To prioritize the safety of user funds, WEEX has established a 1000 BTC user protection fund, with the address publicly disclosed to ensure transparency and accountability.  WEEX takes pride in its team members who possess extensive experience in the blockchain industry, coming from reputable institutions such as Wall Street, Silicon Valley, Citibank, Google, and other top-tier financial companies. The management team is globally distributed across Singapore, Taiwan, Dubai, and other locations. Moreover, WEEX holds MSB financial licenses in the U.S. and Canada, an SVGFSA license, as well as the AUSTRAC license in Australia, further bolstering its credibility and compliance with regulatory requirements.  Adhering to a \"\"customer-first, partner-first\"\" business philosophy, WEEX Exchange strives to deliver highly secure and all-encompassing cryptocurrency services. By fostering \"\"win-win cooperation,\"\" WEEX creates abundant business opportunities for its global partners.",
                  "url": "http://www.weex.com/",
                  "image": "https://assets.coingecko.com/markets/images/1398/small/WEEX-icon-200.png?1706865400",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 91,
                  "trade_volume_24h_btc": 1304.2892899083945,
                  "trade_volume_24h_btc_normalized": 1304.2892899083945
                },
                {
                  "id": "c_patex",
                  "name": "C-Patex",
                  "year_established": null,
                  "country": "Argentina",
                  "description": "",
                  "url": "https://c-patex.com/",
                  "image": "https://assets.coingecko.com/markets/images/246/small/Exchange.jpg?1706864344",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 92,
                  "trade_volume_24h_btc": 1293.7097064883492,
                  "trade_volume_24h_btc_normalized": 1293.7097064883492
                },
                {
                  "id": "raydium-clmm",
                  "name": "Raydium (CLMM)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://raydium.io/swap/",
                  "image": "https://assets.coingecko.com/markets/images/1421/small/raydium.jpeg?1707371905",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 93,
                  "trade_volume_24h_btc": 1093.4251944853565,
                  "trade_volume_24h_btc_normalized": 1093.4251944853565
                },
                {
                  "id": "bit2me",
                  "name": "Bit2Me",
                  "year_established": 2014,
                  "country": "Spain",
                  "description": "",
                  "url": "https://bit2me.com/",
                  "image": "https://assets.coingecko.com/markets/images/1137/small/bit2me.png?1706865155",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 94,
                  "trade_volume_24h_btc": 8564.566762816263,
                  "trade_volume_24h_btc_normalized": 1024.765909848156
                },
                {
                  "id": "bitci",
                  "name": "Bitci TR",
                  "year_established": 2018,
                  "country": "Turkey",
                  "description": "",
                  "url": "https://www.bitci.com.tr/en",
                  "image": "https://assets.coingecko.com/markets/images/450/small/Bitci.jpg?1706864442",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 95,
                  "trade_volume_24h_btc": 950.43121862377,
                  "trade_volume_24h_btc_normalized": 950.43121862377
                },
                {
                  "id": "pancakeswap_new",
                  "name": "PancakeSwap (v2)",
                  "year_established": 2020,
                  "country": null,
                  "description": "",
                  "url": "https://pancakeswap.finance",
                  "image": "https://assets.coingecko.com/markets/images/687/small/pancakeswap.jpeg?1706864634",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 96,
                  "trade_volume_24h_btc": 844.7720301652373,
                  "trade_volume_24h_btc_normalized": 844.7720301652373
                },
                {
                  "id": "uniswap_v3_optimism",
                  "name": "Uniswap V3 (Optimism)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://app.uniswap.org/#/swap",
                  "image": "https://assets.coingecko.com/markets/images/725/small/uniswap-v3.png?1706864684",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 97,
                  "trade_volume_24h_btc": 842.839478412815,
                  "trade_volume_24h_btc_normalized": 842.839478412815
                },
                {
                  "id": "bitdelta",
                  "name": "BitDelta",
                  "year_established": 2023,
                  "country": "Vanuatu",
                  "description": "BitDelta is a global trading platform servicing in 120+ countries with a mission to revolutionize the financial landscape by empowering young individuals and ambitious investors to ignite their trading journey. The platform offers a comprehensive trading experience through a range of innovative features, like Spot Trading, Card Crypto Purchases, Token Launchpad Services and more. Along with these features, BitDelta users are able to diversify their portfolios into a variety of assets, all while using a highly secure asset custodian. With a steadfast commitment to making trading accessible for all, BitDelta aims to create a sophisticated and engaging trading experience where every trade counts.",
                  "url": "https://bitdelta.com/",
                  "image": "https://assets.coingecko.com/markets/images/1317/small/BitDelta_Logo_200x200.png?1706865321",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 98,
                  "trade_volume_24h_btc": 574.8564580482929,
                  "trade_volume_24h_btc_normalized": 574.8564580482929
                },
                {
                  "id": "aerodrome-base",
                  "name": "Aerodrome (Base)",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://aerodrome.finance/",
                  "image": "https://assets.coingecko.com/markets/images/1271/small/aerodrome.jpeg?1706865271",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 99,
                  "trade_volume_24h_btc": 453.01243198923316,
                  "trade_volume_24h_btc_normalized": 453.01243198923316
                },
                {
                  "id": "saucerswap-v2",
                  "name": "Saucerswap V2",
                  "year_established": null,
                  "country": null,
                  "description": "",
                  "url": "https://www.saucerswap.finance/swap",
                  "image": "https://assets.coingecko.com/markets/images/1363/small/SAUCERSWAPv2_1.png?1706865384",
                  "has_trading_incentive": false,
                  "trust_score": 6,
                  "trust_score_rank": 100,
                  "trade_volume_24h_btc": 410.8171966697791,
                  "trade_volume_24h_btc_normalized": 410.8171966697791
                }
              ]
        )
    } catch (error) {
        console.log(error.message)
    }
}

module.exports= feeding_exchange_2_documents