create table users (
  id integer primary key generated by default as identity,
  email text unique not null,
  name text not null,
  username text unique not null,
  phone text,
  website text,
  created_at timestamptz default now()
);

create table posts (
  id integer primary key generated by default as identity,
  title text not null,
  body text,
  published boolean default false,
  author_id integer not null,
  created_at timestamptz default now(),

  constraint fk_author
    foreign key(author_id)
    references users(id)
);

create table address (
  id integer primary key generated by default as identity,
  user_id integer unique,
  street text,
  suite text,
  city text,
  zipcode text,

  constraint fk_user
    foreign key(user_id)
    references users(id)
);

create table todos (
  id integer primary key generated by default as identity,
  user_id integer,
  title text,
  completed boolean default false,
  created_at timestamptz default now(),

  constraint fk_user
    foreign key(user_id)
    references users(id)
);