global:
  scrape_interval: 4s 
  # collect data after 4s 

scrape_configs:
  - job_name: prometheus
    metrics_paths: '/metrics'
    static_configs:
    # from where to collect ie target needs to be the endpoint where metrics are going as res object
      - targets: ["192.168.29.234:4000"]

