version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map port 80 on the host to port 3000 in the container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000" # Map port 4000 on the host to port 4000 in the container
