# Generated by Django 5.2 on 2025-04-28 15:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'City must be at least 2 characters')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='United States', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Country must be at least 2 characters')], verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, 'State must be at least 2 characters')], verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Street name and number', max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Street address must be at least 5 characters'), django.core.validators.RegexValidator(message='Street address must include a street number', regex='\\d')], verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, etc.', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5, 'Suite must be at least 5 characters')], verbose_name='Suite/Apt'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5, 'Zipcode must be at least 5 characters'), django.core.validators.RegexValidator(message='Zipcode must contain only digits', regex='^\\d+$')], verbose_name='ZIP/Postal Code'),
        ),
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.CharField(blank=True, default='Favourites', help_text='What kind of pictures this album will contain', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Category must be at least 2 characters')], verbose_name='Album Category'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='My Photos', help_text='Unique title for your Album', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Album title must be at least 3 characters')], verbose_name='Album Title'),
        ),
        migrations.AlterField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(help_text='URL to the thumbnail version of the image', validators=[django.core.validators.URLValidator(message='Please enter a valid thumbnail URL')], verbose_name='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Title or caption for the image', max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Image title must be at least 3 characters')], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(help_text='URL to the full-size image', validators=[django.core.validators.URLValidator(message='Please enter a valid URL')], verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='Main content of the post', validators=[django.core.validators.MinLengthValidator(20, 'Post body must be at least 20 characters')], verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of the blog post', max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'Post title must be at least 5 characters')], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='Title of the todo item', max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Todo title must be at least 3 characters')], verbose_name='Title'),
        ),
    ]
