apiVersion: v1
kind: Secret
metadata:
    name: backend-secret
    namespace: auth     
type: Opaque
data:
    DATABASE_URL: bW9uZ29kYitzcnY6Ly9zaWRkaGFudGcyMDAyOnV1OUdXV0lWVlR1UmhPNjlAY2x1c3RlcjAubHF6aGpkZC5tb25nb2RiLm5ldC9Vc2Vycw==
    JWT_SECRET: Y2IxZjgzZDRjODVkZGY3ZmVjMjViZmM5NmEwMGM3OWYwMWQxMDAzZjFlN2Q1NmViNDJhMDMxZmZiY2RjOGQ1Yg==