# config_map
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: auth
data:
  APP_SERVER_URL: backend-service
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: auth
  labels:
    app: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: dedsec2002/testing:minikube-frontend
        ports:
        - containerPort: 3000
        env:
        - name: APP_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: APP_SERVER_URL
      imagePullSecrets:
      - name: docker-login
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: auth
spec:
  selector:
    app: nextjs
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000