apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: auth
spec:
  selector:
    app: nextjs
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001