const prompt = require("prompt-sync")();

// COMMON FUNCTION
const array_maker = (callback) => {
    const arr = callback(); // Call the callback function and store its result
    return arr; // Return the array generated by the callback
}

// ARRAY 1
const input1 = () => {
    let size = parseInt(prompt("Enter the size of the Array: "));
    let arr = [];
    for (let i = 0; i < size; i++) {
        let element = parseInt(prompt(`Enter Element ${i + 1}: `));
        arr.push(element);
    }
    return arr; // Return the populated array
};

// ARRAY 2
const input2 = () => {
    let size = parseInt(prompt("Enter the size of the Array: "));
    let arr = [];
    for (let i = 0; i < size; i++) {
        let element = parseInt(prompt(`Enter Element ${i + 1}: `));
        arr.push(element);
    }
    return arr; // Return the populated array
};

// Call the array_maker function for both input1 and input2
const arr1 = array_maker(input1);
const arr2 = array_maker(input2);

console.log("Array 1:", arr1);
console.log("Array 2:", arr2);
arr3=arr1.concat(arr2);
console.log("Array 3:", arr3);
