import Signup from "@/components/Signup"

export const metadata = {
  title: "Signup Page",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div>
      <Signup/>
    </div>
  )
}

export default page