version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - OB-app-network

networks:
  OB-app-network:
    driver: bridge
